language: python
python:
  - "3.6-dev"
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "pypy"
install:
    - "pip install -r requirements-dev.txt"
script:
    - "python setup.py test"
notifications:
      email: false
