language: python
python:
  - "3.6-dev"
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "pypy"

install:
    - "pip install wheel"
    - "pip install -r requirements-dev.txt"

script:
    - "python setup.py test"
    - "python tests/integration_test_udp.py"
    - "pypy -h || python tests/integration_test_tcp.py"
    - "python setup.py bdist_wheel"

after_success:
    - "pip install dist/*.whl"
    - "python -c 'import statsdmetrics'"
    - "python -c 'import statsdmetrics.client'"
    - "python -c 'import statsdmetrics.client.tcp'"

notifications:
      email: false
