language: python
python:
  - "3.7-dev"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

install:
  - "pip install wheel"
  - "pip install -r requirements-dev.txt"

script:
  - "pytest"
  - "python setup.py bdist_wheel -d dist"

after_success:
  - codecov
  - "pip install dist/*.whl"
  - "python -c 'import statsdmetrics'"
  - "python -c 'from statsdmetrics.client import Client'"
  - "python -c 'from statsdmetrics.client.tcp import TCPClient'"

notifications:
  email: false
